name: RL-on-Game
channels:
  - defaults
dependencies:
  - python=3.10.9
  - pip
  - numpy
  - pyparsing
  - jupyterlab
  - scikit-image
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - gym
